### ISSUE TITLE
Do not mention or emojify in a codeblock

### ISSUE THREAD

**Issue by parkr** [jch/html-pipeline#163]
If the `@mention` or `:emoji:` is in a code block, do not transform it. This applies to the HTML, rather than to a Markdown, codeblock.

Related issues:

- https://github.com/jekyll/jemoji/issues/12
- https://github.com/jekyll/jekyll-mentions/issues/7

Thanks!

**Comment by Jastrzebowski** [comment]
@parkr any news about this?

**Comment by parkr** [comment]
The problem is that the Emoji filter runs before the markdown is rendered.

**Comment by simeonwillbanks** [comment]
@parkr In Jekyll, can you send HTML fragments to the Emoji filter?  

As [mentioned](https://github.com/jch/html-pipeline/pull/170#discussion_r23341315) by @jch, "this (*Emoji*) filter is designed to run on HTML fragments, so we should assume that tags is a reasonable input to work with."

**Comment by parkr** [comment]
@simeonwillbanks We'll have to convert it into a `Converter`, rather than a `Generator`.

**Comment by simeonwillbanks** [comment]
OK, cool. I'll close this issue.
