### ISSUE TITLE
possible bug?

### ISSUE THREAD

**Issue by r-lyeh** [jch/html-pipeline#193]
reproduction steps, info and screenshots at https://github.com/github/markup/issues/475

**Comment by JuanitoFatas** [comment]
Probably because GitHub is temporarily disabled Emoji rendering in overly large documents because of performance issues, you should send an email to `support@github.com`.

**Comment by r-lyeh** [comment]
that was it. thanks

**Comment by JuanitoFatas** [comment]
:+1:
