### ISSUE TITLE
List GitHub-deployed versions somewhere?

### ISSUE THREAD

**Issue by wking** [jch/html-pipeline#201]
I've been having trouble with the HTML formatting for emailed comment replies.  For example, [here][1] part my comment is hidden in `email-signature-reply` div.  However, I haven't been able to reproduce this parsing with tests on `email_reply_parser` (see commit wking/email_reply_parser@bd9571a6, Add tests for indented blocks after quotes, 2015-06-18 in my [`test-reply`][2] branch) or in the repository (see my [`test-reply`][3] branch off this repository).  It would help me figure out why the output from this repository (which looks good :) differs from the live HTML I see on GitHub (which has the incorrect `email-signature-reply` divs) if there was a deployed-version endpoint [like there is for GitHub Pages][4].  If that would be leaking to much information, maybe you can compare the deployed versions with what I'm using for tests in my local bundle:

    $ bundle show
    Gems included by the bundle:
      * RedCloth (4.2.9)
      * activesupport (4.2.2)
      * bundler (1.7.3)
      * charlock_holmes (0.6.9.4)
      * email_reply_parser (0.5.8)
      * escape_utils (0.3.2)
      * gemoji (2.1.0)
      * github-linguist (2.6.7)
      * github-markdown (0.6.8)
      * html-pipeline (1.11.0)
      * i18n (0.7.0)
      * json (1.8.3)
      * mime-types (1.25.1)
      * mini_portile (0.6.2)
      * minitest (5.7.0)
      * nokogiri (1.6.5)
      * posix-spawn (0.3.11)
      * pygments.rb (0.4.2)
      * rake (10.4.2)
      * rinku (1.7.3)
      * sanitize (2.1.0)
      * thread_safe (0.3.5)
      * tzinfo (1.2.2)
      * yajl-ruby (1.1.0)

[1]: https://github.com/ipfs/go-ipfs/issues/1393#issuecomment-113299238
[2]: https://github.com/wking/email_reply_parser/tree/test-reply
[3]: https://github.com/wking/html-pipeline/tree/test-reply
[4]: https://pages.github.com/versions/

**Comment by jch** [comment]
@wking sorry for the late reply, I was previously on leave.

html-pipeline is only part of what GitHub uses internally to generate markup. If you're seeing bad email markup, I'd suggest writing in at https://github.com/contact. If I'm misunderstanding what you're asking, please let me know.

Thanks!
