### ISSUE TITLE
Feature request: Strikethrough if issue is closed

### ISSUE THREAD

**Issue by shadowwalkersb** [jch/html-pipeline#202]
It would be very useful to show an issue as strike-through formatted if it is closed.

**Comment by simeonwillbanks** [comment]
@shadowwalkersb Thanks for the idea!  If you're asking about a specific change to Issues on GitHub, please email support@github.com.  Thanks again.  :smile:

**Comment by jdickey** [comment]
@shadowwalkersb I think, perhaps charitably, that what @shadowwalkersb meant to say was along the lines of

> If you can show a use case that involves changes to HTML::Pipeline code rather than Github-supplied Gems (that are used *by* HTML::Pipeline), details would be useful. Otherwise, you're more likely to get results talking directly to GitHub (and providing use-case details to *them*).

**Comment by simeonwillbanks** [comment]
Well said @jdickey. Thank you!  :smile:
