### ISSUE TITLE
Need help fixing a non-security issue…

### ISSUE THREAD

**Issue by ytrezq** [jch/html-pipeline#214]
Before I submit any pull requests on that page, just need help with a question as I’m unable to reproduce the behaviour locally :

Where is the code responsible for escaping the content between 2 not whitelisted/disabled html tags *(I also think to the dependencies)* ?
So that :

     <title><a href="https://www.google.fr">test</a></title>
renders :
<title><a href="https://www.google.fr">test</a></title>
However, doing the same locally :

    echo "<title><a href="https://www.google.fr">test</a></title>" | ./html-pipeline Sanitization
renders :
<a href="https://www.google.fr">test</a>
which means : `<a href="https://www.google.fr">test</a>`in plain text.

**Comment by jch** [comment]
What pipeline and filter are you using?

**Comment by ytrezq** [comment]
@jch : See the update.

**Comment by jch** [comment]
> as I’m unable to reproduce the behaviour locally

What is your server implementation? If you're asking about github.com markup, this library is not tied to the site's implementation and you should contact https://github.com/support

**Comment by ytrezq** [comment]
Ok, I thought the library version used by github.com was the same as this public one. Sorry…

**Comment by jch** [comment]
@ytrezq no worries ;) I'm going to close this for now
