### ISSUE TITLE
Accessibility-related HTML isn't whitelisted

### ISSUE THREAD

**Issue by fstorr** [jch/html-pipeline#215]
It would be very useful to allow accessibility-related HTML to be whitelisted. Specifically:
1. The `<caption>` element for tables
2. The `aria-labelledby`, `aria-label`, and `aria-describedby` attributes.

Allowing these will help improve the accessibility of documents to meet some of the WCAG 2.0 requirements around text-alternatives, information and relationships, and names, roles, and values.

**Comment by edent** [comment]
Similar `<figure>` and `<figcaption>` would be helpful.

**Comment by jrfnl** [comment]
:+1: Please also consider `aria-hidden` as allowed.

**Comment by gjtorikian** [comment]
Of course! Sorry to see that this wasn't addressed earlier.

**Comment by jrfnl** [comment]
@gjtorikian Does that mean it will be addressed by you now or should I (non-ruby dev) create a PR for it ?

**Comment by gjtorikian** [comment]
This is now out at 2.8.3.

**Comment by jrfnl** [comment]
@gjtorikian Thank you **so* much! Your quick response to this is much appreciated.

**Comment by gjtorikian** [comment]
No worries. I love accessibility.
