### ISSUE TITLE
Add SmartQuotes filter

### ISSUE THREAD

**Issue by benbalter** [jch/html-pipeline#220]
There's a few scenarios where we'd prefer content be published with [smart quotes](https://www.fastcodesign.com/3018353/be-smart-dont-use-dumb-quote-marks), and based on our implementation, the most elegant solution would be to bake the smartification into HTML Pipeline.

It looks like [Rubypants](https://github.com/jmcnevin/rubypants) is a Ruby port of SmartyPants, the library used by things like WordPress.

Before I went too far down the :rabbit: hole, wanted to gauge interest in a PR adding a SmartQuotes filter that used Ruby pants as an optional dependency.

/cc @cameronmcefee

**Comment by jch** [comment]
If you do decide to build it, I'd recommend building as a separate gem and linking to it from the readme. We've been avoiding adding more dependencies to this gem and also it's easier for the original author to maintain it.

**Comment by benbalter** [comment]
>  I'd recommend building as a separate gem and linking to it from the readme. 

Just to confirm, you're suggesting I create a gem that adds a new filter to HTML pipeline?

**Comment by jch** [comment]
@benbalter yep! Examples are in this section of the readme: https://github.com/jch/html-pipeline#3rd-party-extensions. Closing for now, but feel free to send a PR with a link to your project if you build it.
