### ISSUE TITLE
2.2.1 release

### ISSUE THREAD

**Issue by getaaron** [jch/html-pipeline#225]
Can you please tag & release 2.2.1 to [Rubygems](https://rubygems.org/gems/html-pipeline) so I can install the fix using `gem install`?

**Comment by jch** [comment]
@getaaron released!

@JuanitoFatas I didn't see a PR for releasing 2.2.1. Did you merge that directly to master or did I miss it somewhere?

**Comment by JuanitoFatas** [comment]
@jch This commit https://github.com/jch/html-pipeline/commit/c26c42966e424b455a8f3711abe5d62e6b664964 in #208. I thought you see it. Sorry I should remind you!
