### ISSUE TITLE
Allow backslash-escape for @mention and emoji

### ISSUE THREAD

**Issue by zcorpan** [jch/html-pipeline#232]
Most syntax in GFM can be escaped in one way or another, but I found no good way to escape @mention syntax and emoji syntax other than inserting a U+200B ZERO WITH SPACE after @ or : 

It should be possible to do `\@mention` and `\:+1\:` and have the backslash removed and mention/emoji disabled.

**Comment by kbrock** [comment]
short term work around, I put them in backticks: `@mention`

but yes, this sounds good

**Comment by MikhailTymchukDX** [comment]
+1
I was lucky enough when I wrote about the ASP.NET @Page directive not to mention such a person, but who knows, what directive can make a collision with existing user...

**Comment by gjtorikian** [comment]
> come on github, this is basic...

This is an open source project managed by volunteers that are unaffiliated with GitHub. If it's so basic consider opening a pull request.

**Comment by nallar** [comment]
oddly, in this issue `:yarn:` in a code block stays as text. On an issue on the gradle repository, they're being changed even in the code blocks: https://github.com/gradle/gradle/issues/13044

**Comment by gjtorikian** [comment]
GitHub does not use this project for rendering their comments. I suggest writing an email to their Support team about it.

**Comment by zcorpan** [comment]
Testing again with backslashes: \@mention \:+1\:

**Comment by zcorpan** [comment]
So backslashes now disable @ but not : in emojis, in GitHub comments. I can contact GitHub support.

**Comment by zcorpan** [comment]
No wait. "@mention" is never linked. Testing again: \@zcorpan

**Comment by gjtorikian** [comment]
Closed as this is not the place to log GitHub bugs.
