### ISSUE TITLE
Emoji <img> tags does not pass W3C validationg

### ISSUE THREAD

**Issue by FiveYellowMice** [jch/html-pipeline#234]
I use jekyl/jemoji to generate emojis. However the `<img>` tags use align attribute which is deprecated.

How about using style attribute instead?

I've opened an issue on jekyll/jemoji#30.

**Comment by simeonwillbanks** [comment]
[`EmojiFilter#emoji_image_tag`](https://github.com/jch/html-pipeline/blob/c8e7613161e6bf914ed1672804d45761c92fd55c/lib/html/pipeline/emoji_filter.rb#L72-L75) contains the HTML.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

> `align` Deprecated since [HTML4.01](https://developer.mozilla.org/en-US/docs/Web/HTML), Obsolete since [HTML5](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5) 
> Use the `vertical-align` CSS property 
> The alignment of the image with respect to its surrounding context.

I'm :+1: removing. :smile:

**Comment by kbrock** [comment]
For some ideas around the css, you may want to look [here](https://github.com/jedcn/reveal-ck/blob/master/files/reveal-ck/css/reveal-ck.css)

good luck

**Comment by adammacias** [comment]
:+1:

**Comment by borisschapira** [comment]
Hello! First, thanks to the people maintaining this. I'm gonna try to help, but I'm not sure I can. About this issue, may I propose another path: keeping the current markup (for backward compatibility) but allowing user to propose a custom markup ? That way, [jekyll/jemoji](https://github.com/jekyll/jemoji) could offer the capacity to users to propose their own template.

**Comment by rajsite** [comment]
@borisschapira That would be awesome, I just reported this issue https://github.com/jekyll/jemoji/issues/42 but I'm guessing the templating you propose would need to be implemented first.

To briefly re-state that issue, templating would be useful to enable using emoji with [AMP HTML](https://github.com/ampproject/amphtml) which requires using the `amp-img` tag instead of `img`.

**Comment by JuanitoFatas** [comment]
`<img>` tag attributes now can be override, please see #258.
