### ISSUE TITLE
Allow embedding of JSON-LD

### ISSUE THREAD

**Issue by alexmilowski** [jch/html-pipeline#250]
This may be a completely non-starter but the current techniques for embedding JSON-LD into HTML is via the script element ([1],[2]) with a type of "application/ld+json".  One option would be to only allow a script tag through that has this particular media type value in the "type" attribute.

Another would be to get the JSON-LD folks to use a less dangerous element! :)

[1] http://www.w3.org/TR/json-ld/#embedding-json-ld-in-html-documents
[2] https://developers.google.com/schemas/formats/json-ld

**Comment by vallieres** [comment]
I do have the same problem with jekyll-mentions, that is now using html-pipeline, my json-ld gets replaced improperly. Refer to https://github.com/jekyll/jekyll-mentions/issues/30 for details (or I can open another ticket if you prefer, let me know).

**Comment by mbirth** [comment]
Same here. See gettalong/kramdown#426 .
