### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by connorshea** [jch/html-pipeline#252]
Will html-pipeline be updated with ActiveSupport 5 and therefore Rails 5 support any time soon?

**Comment by jch** [comment]
I haven't had time to set up tests with a new gemfile. It shouldn't be difficult though.

**Comment by connorshea** [comment]
Awesome! Rails 5.0.0.beta4 just came out, and allegedly rc1 will be coming in the next few weeks. It'd be great to have support for it :)

**Comment by jaykilleen** [comment]
@connorshea what sort of issues are you having? I am also running Rails 5.0.0.beta4 and am getting the syntax highlighting and tables don't appear to be working. Not sure if it is me though :/

**Comment by connorshea** [comment]
@jaykilleen Unfortunately because [the gemspec requires activesupport < 5](https://github.com/jch/html-pipeline/blob/master/html-pipeline.gemspec#L19) we can't use it without forking the gem and changing that ourselves. We haven't been able to test it with Rails 5 yet because of other gems as well, despite my having spent the last few months trying to update gems >.<

**Comment by n-rodriguez** [comment]
hi there! any news?

**Comment by n-rodriguez** [comment]
Thanks!

**Comment by JuanitoFatas** [comment]
@connorshea Please try 2.4.2 on Rails 5, please report if any problem, thank you.

**Comment by connorshea** [comment]
Thank you @JuanitoFatas! We'll try upgrading and report back if there are any problems.
