### ISSUE TITLE
Missing context keys for HTML::Pipeline::EmojiFilter: :asset_root

### ISSUE THREAD

**Issue by marcocanderle** [jch/html-pipeline#262]
Hi,

I'm with a Rails 5 application and adding html_pipeline gem with the EmojiFilter extension so that I can process the text sent by the users and filter the emojies.

I have the following:

    def filtered_content
        pipeline = HTML::Pipeline.new [
         HTML::Pipeline::PlainTextInputFilter,
         HTML::Pipeline::MarkdownFilter,
         HTML::Pipeline::SanitizationFilter,
         HTML::Pipeline::AutolinkFilter,
         HTML::Pipeline::EmojiFilter
        ]
       pipeline.call(content)[:output].to_s
    end

I followed the usual steps adding the gemoji gem so that I can use the EmojiFilter, but when I add it to the pipeline declaration and try to use the pipeline I get the error:

    Missing context keys for HTML::Pipeline::EmojiFilter: :asset_root

I added this on my assets.rb initializer:

      Rails.application.config.assets.paths << Emoji.images_path
      Rails.application.config.assets.precompile << "emoji/**/*.png"

And also ran "rake emoji" but the error is still there.

Any ideas of I could solve this?

Thanks!
Marco

**Comment by JuanitoFatas** [comment]
Hi! The [asset_root is the base url to link emoji sprite](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/emoji_filter.rb#L14), not related to sprockets.

So you need to change your html-pipeline code:

```ruby
def filtered_content
    pipeline = HTML::Pipeline.new [
     HTML::Pipeline::PlainTextInputFilter,
     HTML::Pipeline::MarkdownFilter,
     HTML::Pipeline::SanitizationFilter,
     HTML::Pipeline::AutolinkFilter,
     HTML::Pipeline::EmojiFilter
    ], { asset_root: <the url of your assets> # <------
   pipeline.call(content)[:output].to_s
end
```

Hope this help! 😊

**Comment by marcocanderle** [comment]
That's exactly what I was looking for!
Thanks a lot @JuanitoFatas 

Perhaps that exact example could be on the readme file?

Thanks a lot for your help and for this gem!
