### ISSUE TITLE
Github Flavoured Markdown table support

### ISSUE THREAD

**Issue by jaykilleen** [jch/html-pipeline#269]
Sorry if I am missing something obvious here but I have tried implementing the [GFM syntax for tables][1] into one of my projects.

I have set gfm => true in my application helper and am able to successfully render code blocks, emojis, links and other functionality.

```ruby
  def markdownify(content)
    pipeline_context = {gfm: true, asset_root: "https://a248.e.akamai.net/assets.github.com/images/icons/"}
    pipeline = HTML::Pipeline.new [
        HTML::Pipeline::MarkdownFilter,
        HTML::Pipeline::EmojiFilter,
        HTML::Pipeline::SanitizationFilter
        ], pipeline_context
        pipeline.call(content)[:output].to_s.html_safe
  end
```

Is there something else I need to have this functionality?

[1]: https://help.github.com/articles/organizing-information-with-tables/

**Comment by amitpatra** [comment]
Try to add `:commonmarker_extensions => [ :table]`.

**Comment by gjtorikian** [comment]
Yes, we ought to do a better job documenting here, but @amitpatra is correct (based on https://github.com/jch/html-pipeline/blob/010a6bdeace506725d619b95812eb6c4c55ca4c0/lib/html/pipeline/markdown_filter.rb#L11) and you can pass any of [the Commonmarker extensions](https://github.com/gjtorikian/commonmarker#extensions) through.
