### ISSUE TITLE
RFC5122: XMPP URI

### ISSUE THREAD

**Issue by Neustradamus** [jch/html-pipeline#289]
Can you add XMPP URI ?

Examples:
- xmpp:username@domain.tld
- xmpp:username@domain.tld?message
- xmpp:mucroom@domain.tld?join

RFC 5122: https://tools.ietf.org/html/rfc5122

The problem is that it is replaced by mailto:

Thanks in advance.

**Comment by gjtorikian** [comment]
Add it to what? The `SanitizationFilter`?

We'll gladly accept any pull requests for reasonable changes, which this sounds like. 👍

**Comment by Neustradamus** [comment]
Thanks @gjtorikian!
Can you inform me when it will be in github production?

**Comment by Neustradamus** [comment]
@gjtorikian: maybe @jch can see directly?
Or other can do it?
@d12, @cheshire137, @dgraham, @kenyonj, ...

**Comment by gjtorikian** [comment]
Please don't ping random people. Please use the form I linked you to.
