### ISSUE TITLE
New feature request for hashtags # filter 

### ISSUE THREAD

**Issue by lengerfulluse** [jch/html-pipeline#301]
Is that possible to add a **hashtag #** filter just like twitter, as it's a very common use case for html filter

seems there's already an exist implementation on top of **html-pipeline**, called [html-pipeline-hashtag](https://github.com/mr-dxdy/html-pipeline-hashtag), maybe we can request a pull request.

**Comment by gjtorikian** [comment]
I'd certainly accept a PR from @mr-dxdy if they're interested in upstreaming that project here. Otherwise, the beauty of HTML-Pipeline is that users can plug-in any filter that they want.

As there's nothing really actionable here, and a third-party extension exists, I'm closing this out.
