### ISSUE TITLE
Update CHANGELOG

### ISSUE THREAD

**Issue by sj26** [jch/html-pipeline#315]
The changelog seems to be missing entries since 2.6.0:

https://github.com/jch/html-pipeline/blob/master/CHANGELOG.md

What's changed?

**Comment by gjtorikian** [comment]
I'm pretty much the only maintainer here, and I don't have the time or energy to implement some kind of automation for this, I'm sorry to say. 

It's probably not super user-friendly, but I tag every release, and [you can look at the diff between releases](https://github.com/jch/html-pipeline/compare/v2.6.0...v2.12.0) to identify any minor/patch changes.

**Comment by sj26** [comment]
No worries, maybe I can help :-)

#316
